# Generated by Django 5.2.15 on 2026-06-13 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meditations", "0002_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Practice",
            fields=[
                (
                    "name",
                    models.SlugField(
                        max_length=200, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=200)),
                ("items", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
