# Generated by Django 5.2.15 on 2026-06-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meditations", "0003_practice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assembledoutput",
            name="audio_file",
            field=models.FileField(max_length=300, upload_to="outputs/"),
        ),
        migrations.AlterField(
            model_name="asset",
            name="audio_file",
            field=models.FileField(max_length=300, upload_to="assets/"),
        ),
        migrations.AlterField(
            model_name="component",
            name="audio_file",
            field=models.FileField(blank=True, max_length=300, upload_to="components/"),
        ),
    ]
