# Generated by Django 6.0.6 on 2026-06-16

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def migrate_groups_forward(apps, schema_editor):
    """Create Group records from existing category group strings and update FKs."""
    Category = apps.get_model("meditations", "Category")
    Group = apps.get_model("meditations", "Group")

    # Collect distinct group names
    group_names = set()
    for cat in Category.objects.all():
        if cat.group:
            group_names.add(cat.group)

    # Create Group records
    group_map = {}
    for gname in group_names:
        slug = slugify(gname) or f"group-{gname[:20]}"
        group, _ = Group.objects.get_or_create(
            name=slug,
            defaults={"display_name": gname, "sort_order": 0},
        )
        group_map[gname] = slug

    # Update categories to point to the new slugs
    for cat in Category.objects.all():
        if cat.group and cat.group in group_map:
            cat.group = group_map[cat.group]
            cat.save(update_fields=["group"])
        elif cat.group:
            # Clear invalid group references
            cat.group = ""
            cat.save(update_fields=["group"])


def migrate_groups_backward(apps, schema_editor):
    """Convert FK back to display_name strings."""
    Category = apps.get_model("meditations", "Category")
    Group = apps.get_model("meditations", "Group")

    group_map = {g.name: g.display_name for g in Group.objects.all()}
    for cat in Category.objects.all():
        if cat.group and cat.group in group_map:
            cat.group = group_map[cat.group]
            cat.save(update_fields=["group"])


class Migration(migrations.Migration):

    dependencies = [
        ("meditations", "0005_category_group"),
    ]

    operations = [
        # 1. Create Group table
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "name",
                    models.SlugField(
                        max_length=200, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("display_name", models.CharField(max_length=200)),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "display_name"],
            },
        ),
        # 2. Populate groups and update category.group strings to slugs
        migrations.RunPython(migrate_groups_forward, migrate_groups_backward),
        # 3. Convert the field to FK
        migrations.AlterField(
            model_name="category",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="categories",
                to="meditations.group",
            ),
        ),
    ]
