# Generated by Django 6.0.6 on 2026-06-13 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "filename",
                    models.CharField(
                        max_length=200, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("audio_file", models.FileField(upload_to="assets/")),
                ("trim_meta", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="Meditation",
            fields=[
                (
                    "name",
                    models.SlugField(
                        max_length=200, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=200)),
                ("category", models.CharField(default="uncategorised", max_length=100)),
                ("instructions", models.JSONField(blank=True, default=dict)),
                ("script", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stage_id", models.CharField(max_length=200)),
                ("script", models.JSONField(blank=True, default=list)),
                ("variables", models.JSONField(blank=True, default=dict)),
                (
                    "meditation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="meditations.meditation",
                    ),
                ),
            ],
            options={
                "unique_together": {("meditation", "stage_id")},
            },
        ),
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seg_id", models.CharField(max_length=200)),
                ("text_hash", models.CharField(blank=True, max_length=8)),
                ("timestamps", models.JSONField(blank=True, default=list)),
                ("trim_meta", models.JSONField(blank=True, default=dict)),
                ("audio_file", models.FileField(blank=True, upload_to="components/")),
                (
                    "meditation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="meditations.meditation",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="meditations.stage",
                    ),
                ),
            ],
            options={
                "unique_together": {("meditation", "stage", "seg_id")},
            },
        ),
        migrations.CreateModel(
            name="AssembledOutput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("script_hash", models.CharField(max_length=10)),
                ("audio_file", models.FileField(upload_to="outputs/")),
                ("duration", models.FloatField()),
                (
                    "meditation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outputs",
                        to="meditations.meditation",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="meditations.stage",
                    ),
                ),
            ],
            options={
                "unique_together": {("meditation", "stage", "script_hash")},
            },
        ),
    ]
