# Generated by Django 5.2.15 on 2026-06-17 14:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meditations", "0008_rbac"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="meditation",
            name="shared_with",
            field=models.ManyToManyField(
                blank=True,
                related_name="shared_meditations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="practice",
            name="shared_with",
            field=models.ManyToManyField(
                blank=True, related_name="shared_practices", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
