# Generated by Django 5.2.15 on 2026-06-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meditations", "0009_shared_with"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitelink",
            name="name",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
