# Generated by Django 5.2.15 on 2026-06-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meditations", "0010_invite_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="display_name",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
