# Generated by Django 5.2.15 on 2026-06-17 15:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meditations", "0012_group_created_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="shared_with",
            field=models.ManyToManyField(
                blank=True,
                related_name="shared_categories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="shared_with",
            field=models.ManyToManyField(
                blank=True, related_name="shared_groups", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
