# Generated by Django 5.2.15 on 2026-06-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meditations", "0013_group_category_shared_with"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="show_public_to_viewers",
            field=models.BooleanField(default=True),
        ),
    ]
