# Generated by Django 5.2.15 on 2026-06-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meditations", "0014_show_public_to_viewers"),
    ]

    operations = [
        migrations.AddField(
            model_name="vieweraccess",
            name="show_public",
            field=models.BooleanField(default=True),
        ),
    ]
