# Generated by Django 5.2.15 on 2026-06-17 20:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meditations", "0015_viewer_show_public"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PracticeSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("practice_display", models.CharField(blank=True, max_length=200)),
                ("week", models.IntegerField()),
                ("day", models.IntegerField()),
                ("day_label", models.CharField(blank=True, max_length=200)),
                ("duration", models.FloatField(default=0)),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "practice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="meditations.practice",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-completed_at"],
            },
        ),
    ]
