# Generated by Django 5.2.15 on 2026-06-17 21:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meditations", "0016_practice_session"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="meditation",
            name="category",
            field=models.CharField(
                db_index=True, default="uncategorised", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="meditation",
            name="is_public",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="practice",
            name="is_public",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name="practicesession",
            index=models.Index(
                fields=["user", "-completed_at"], name="meditations_user_id_cc983b_idx"
            ),
        ),
    ]
