# Generated by Django 5.2.15 on 2026-06-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meditations", "0017_db_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_photo",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
