# Generated by Django 5.2.15 on 2026-06-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meditations", "0018_add_profile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_public",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="group",
            name="is_public",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
