# Generated by Django 5.2.15 on 2026-06-19 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def assign_category_owners(apps, schema_editor):
    """Assign each category to the user who owns the most meditations in it."""
    Category = apps.get_model("meditations", "Category")
    Meditation = apps.get_model("meditations", "Meditation")
    from collections import Counter

    for cat in Category.objects.all():
        owners = Meditation.objects.filter(
            category=cat.name, created_by__isnull=False,
        ).values_list("created_by", flat=True)
        if not owners:
            continue
        most_common_id = Counter(owners).most_common(1)[0][0]
        cat.created_by_id = most_common_id
        cat.save(update_fields=["created_by"])


class Migration(migrations.Migration):

    dependencies = [
        ("meditations", "0019_add_is_public_to_group_and_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exercise_categories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(assign_category_owners, migrations.RunPython.noop),
    ]
