# Generated by Django 5.2.15 on 2026-06-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meditations", "0022_add_signup_token_and_invited_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[("generated", "Generated"), ("uploaded", "Uploaded")],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="variable_values",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
