# Generated by Django 5.2.15 on 2026-06-22 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meditations", "0023_add_component_source_and_variable_values"),
    ]

    operations = [
        migrations.CreateModel(
            name="VariableRecording",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seg_id", models.CharField(max_length=200)),
                ("variable_name", models.CharField(max_length=100)),
                ("variable_value", models.CharField(max_length=100)),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        choices=[("generated", "Generated"), ("uploaded", "Uploaded")],
                        max_length=20,
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="variable_recordings",
                        to="meditations.component",
                    ),
                ),
                (
                    "meditation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variable_recordings",
                        to="meditations.meditation",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variable_recordings",
                        to="meditations.stage",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("meditation", "stage", "seg_id", "variable_name", "variable_value")
                },
            },
        ),
    ]
