# Generated by Django 5.2.15 on 2026-06-22 11:37

import django.db.models.deletion
from django.db import migrations, models


def backfill_audio_clips(apps, schema_editor):
    """Create AudioClip records from existing Component data."""
    Component = apps.get_model("meditations", "Component")
    AudioClip = apps.get_model("meditations", "AudioClip")

    for comp in Component.objects.exclude(audio_file="").exclude(text_hash=""):
        clip, _ = AudioClip.objects.get_or_create(
            text_hash=comp.text_hash,
            defaults={
                "audio_file": comp.audio_file,
                "timestamps": comp.timestamps or [],
                "source": comp.source or "generated",
            },
        )
        comp.audio_clip = clip
        comp.save(update_fields=["audio_clip"])


class Migration(migrations.Migration):

    dependencies = [
        ("meditations", "0024_variable_recording"),
    ]

    operations = [
        migrations.CreateModel(
            name="AudioClip",
            fields=[
                (
                    "text_hash",
                    models.CharField(max_length=16, primary_key=True, serialize=False),
                ),
                ("audio_file", models.FileField(max_length=300, upload_to="clips/")),
                ("timestamps", models.JSONField(blank=True, default=list)),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        choices=[("generated", "Generated"), ("uploaded", "Uploaded")],
                        max_length=20,
                    ),
                ),
            ],
        ),
        # Add audio_clip FK before removing old fields so we can backfill
        migrations.AddField(
            model_name="component",
            name="audio_clip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="components",
                to="meditations.audioclip",
            ),
        ),
        migrations.RunPython(backfill_audio_clips, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="component",
            name="audio_file",
        ),
        migrations.RemoveField(
            model_name="component",
            name="source",
        ),
        migrations.RemoveField(
            model_name="component",
            name="text_hash",
        ),
        migrations.RemoveField(
            model_name="component",
            name="timestamps",
        ),
        migrations.RemoveField(
            model_name="component",
            name="variable_values",
        ),
        migrations.RemoveField(
            model_name="variablerecording",
            name="component",
        ),
        migrations.AddField(
            model_name="variablerecording",
            name="audio_clip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="variable_recordings",
                to="meditations.audioclip",
            ),
        ),
    ]
