# Generated by Django 5.2.15 on 2026-06-23 18:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meditations", "0027_variable_key"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="speechsegmentaudio",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="useruploadedclip",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="variablerecording",
            name="variable_key",
            field=models.CharField(max_length=500),
        ),
        migrations.CreateModel(
            name="ActivityEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("event", models.CharField(max_length=50)),
                ("page", models.CharField(blank=True, max_length=500)),
                ("target", models.CharField(blank=True, max_length=500)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("session_id", models.CharField(blank=True, max_length=64)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="meditations_user_id_0d27b0_idx",
                    ),
                    models.Index(fields=["event"], name="meditations_event_eae29e_idx"),
                    models.Index(
                        fields=["session_id"], name="meditations_session_183b4d_idx"
                    ),
                ],
            },
        ),
    ]
