# Generated by Django 5.2.15 on 2026-06-23 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meditations", "0028_activity_event"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ActivityEvent",
        ),
    ]
