# Generated by Django 5.2.15 on 2026-06-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meditations", "0030_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="session_id",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
