# Generated by Django 5.2.15 on 2026-06-27 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meditations", "0034_add_stage_assignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="practicesession",
            name="meditation_display",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="practicesession",
            name="meditation_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="practicesession",
            name="stage_id",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="practicesession",
            name="stage_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="practicesession",
            name="day",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="practicesession",
            name="practice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="meditations.practice",
            ),
        ),
        migrations.AlterField(
            model_name="practicesession",
            name="week",
            field=models.IntegerField(default=0),
        ),
    ]
