# Generated by Django 5.2.15 on 2026-06-30 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meditations", "0035_exercise_session_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="stage",
            name="before_you_begin",
            field=models.TextField(blank=True, default=""),
        ),
    ]
